version: 2.1

orbs:
  python: circleci/python@2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install uv
          command: curl -LsSf https://astral.sh/uv/install.sh | sh

      - run:
          name: Create and Activate Virtual Environment
          command: |
            uv venv .venv
            echo 'export PATH=".venv/bin:$PATH"' >> $BASH_ENV
            echo "export PYTHONPATH=$PWD/src" >> $BASH_ENV  # Ensure src/ is recognized
            source .venv/bin/activate

      - run:
          name: Install Dependencies
          command: |
            uv pip install ".[dev]"
            uv pip install mypy ruff pytest pytest-cov  # Ensure all dependencies

      - run:
          name: Run Static Analysis
          command: |
            mypy src tests
            ruff check . --config pyproject.toml
      # Run unit tests
      - run:
          name: Run Unit Tests
          command: |
            nose2 --with-coverage --coverage-report xml --coverage-report html --junit-xml-path=test-results/unit.xml discover src/calculator/test src/logger/test src/notifier/test
            mv coverage.xml unit-coverage.xml
            mv htmlcov unit-htmlcov
            coverage report --fail-under=70

      # Run integration tests and append coverage
      - run:
          name: Run Integration Tests
          command: |
            COVERAGE_FILE=.coverage.integration nose2 --with-coverage --coverage-report xml --coverage-report html --junit-xml-path=test-results/integration.xml discover tests/integration
            mv coverage.xml integration-coverage.xml
            mv htmlcov integration-htmlcov
            coverage report --fail-under=70

      # Run e2e tests and generate final coverage report
      - run:
          name: Run End-to-End Tests and Check Coverage
          command: |
            COVERAGE_FILE=.coverage.e2e nose2 --with-coverage --coverage-report xml --coverage-report html --junit-xml-path=test-results/e2e.xml discover tests/e2e
            mv coverage.xml e2e-coverage.xml
            mv htmlcov e2e-htmlcov
            coverage report --fail-under=70
            
            # Generate combined report (optional)
            coverage combine .coverage .coverage.integration .coverage.e2e
            coverage report --fail-under=70
            coverage xml -o combined-coverage.xml
            coverage html -d combined-htmlcov

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: htmlcov
          destination: coverage-report

workflows:
  main:
    jobs:
      - build-and-test
