version: 2.1

orbs:
  python: circleci/python@2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install uv
          command: curl -LsSf https://astral.sh/uv/install.sh | sh

      - run:
          name: Create and Activate Virtual Environment
          command: |
            uv venv .venv
            echo 'export PATH=".venv/bin:$PATH"' >> $BASH_ENV
            echo "export PYTHONPATH=$PWD/src" >> $BASH_ENV
            source .venv/bin/activate

      - run:
          name: Install Dependencies
          command: |
            uv pip install ".[dev]"
            uv pip install mypy ruff nose2 coverage

      - run:
          name: Cleanup old coverage data
          command: |
            coverage erase
            rm -f .coverage*

      - run:
          name: Run Static Analysis
          command: |
            mypy src tests
            ruff check . --config pyproject.toml

      - run:
          name: Run Unit Tests
          command: |
            touch .coverage.calculator
            COVERAGE_FILE=.coverage.calculator nose2 -v -s src/calculator/test/ --with-coverage --coverage=src.calculator
            touch .coverage.logger
            COVERAGE_FILE=.coverage.logger nose2 -v -s src/logger/test/ --with-coverage --coverage=src.logger
            touch .coverage.notifier
            COVERAGE_FILE=.coverage.notifier nose2 -v -s src/notifier/test/ --with-coverage --coverage=src.notifier

      - run:
          name: Run Integration Tests
          command: |
            touch .coverage.integration
            COVERAGE_FILE=.coverage.integration nose2 -s tests/integration/ --plugin=nose2.plugins.junitxml --junit-xml-path=test-results/integration.xml --with-coverage

      - run:
          name: Run End-to-End Tests
          command: |
            touch .coverage.e2e
            COVERAGE_FILE=.coverage.e2e nose2 -s tests/e2e/ --plugin=nose2.plugins.junitxml --junit-xml-path=test-results/e2e.xml --with-coverage

      - run:
          name: Final Coverage Report
          command: |
            coverage combine .coverage.calculator .coverage.logger .coverage.notifier .coverage.integration .coverage.e2e
            coverage report --fail-under=70
            coverage xml -o total-coverage.xml
            coverage html -d total-htmlcov

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: total-htmlcov
          destination: total-coverage-report

      - store_artifacts:
          path: total-coverage.xml
          destination: coverage-reports/total-coverage.xml

workflows:
  main:
    jobs:
      - build-and-test
