version: 2.1

orbs:
  python: circleci/python@2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Dependencies
          command: pip install ".[dev]"
      - run:
          name: Run Static Analysis
          command: |
            mypy src tests
            ruff check .
      - run:
          name: Run Tests
          command: |
            pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
          destination: coverage-report

workflows:
  main:
    jobs:
      - build-and-test
