version: 2.1

orbs:
  python: circleci/python@2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install uv
          command: curl -LsSf https://astral.sh/uv/install.sh | sh

      - run:
          name: Create and Activate Virtual Environment
          command: |
            uv venv .venv
            echo 'export PATH=".venv/bin:$PATH"' >> $BASH_ENV
            echo "export PYTHONPATH=$PWD/src" >> $BASH_ENV  # Ensure src/ is recognized
            source .venv/bin/activate

      - run:
          name: Install Dependencies
          command: |
            uv pip install ".[dev]"
            uv pip install mypy ruff pytest pytest-cov  # Ensure all dependencies

      - run:
          name: Run Static Analysis
          command: |
            mypy src tests
            ruff check . --config pyproject.toml
      # Run unit tests
      - run:
          name: Run Unit Tests
          command: |
            nose2 -v -s src/calculator/test/ --with-coverage --coverage=src.calculator

            COVERAGE_FILE=.coverage.logger nose2 -v -s src/logger/test/ --with-coverage --coverage=src.logger

            COVERAGE_FILE=.coverage.notifier nose2 -v -s src/notifier/test/ --with-coverage --coverage=src.notifier

            coverage combine .coverage .coverage.logger .coverage.notifier

            coverage report --fail-under=70
            coverage xml -o unit-coverage.xml 
            coverage html -d unit-htmlcov

      # Run integration tests and append coverage
      - run:
          name: Run Integration Tests
          command: |
            COVERAGE_FILE=.coverage.integration nose2 -s tests/integration/ --plugin=nose2.plugins.junitxml --junit-xml-path=test-results/integration.xml --with-coverage
            coverage report --fail-under=70
            coverage xml -o integration-coverage.xml
            coverage html -d integration-htmlcov

      # Run e2e tests and generate final coverage report
      - run:
          name: Run End-to-End Tests and Check Coverage
          command: |
            COVERAGE_FILE=.coverage.e2e nose2 -s tests/e2e/ --plugin=nose2.plugins.junitxml --junit-xml-path=test-results/e2e.xml --with-coverage
            coverage report --fail-under=70
            coverage xml -o e2e-coverage.xml
            coverage html -d e2e-htmlcov

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: htmlcov
          destination: coverage-report

workflows:
  main:
    jobs:
      - build-and-test
