from typing import Protocol, runtime_checkable


@runtime_checkable
class ChannelEntity(Protocol):
    def get_id(self) -> str: ...
    def get_name(self) -> str: ...
    def list_users(self) -> list[str]: ...

@runtime_checkable
class ChannelService(Protocol):
    def create_channel(self, name: str) -> ChannelEntity: ...
    def join_channel(self, user_id: str, channel_id: str) -> bool: ...
