from collections.abc import Sequence
from typing import Protocol, runtime_checkable


@runtime_checkable
class IUser(Protocol):
    def get_id(self) -> str: ...
    def get_username(self) -> str: ...
    def list_channels(self) -> Sequence[str]: ...

@runtime_checkable
class IUserService(Protocol):
    def register(self, username: str) -> IUser: ...
    def login(self, username: str) -> IUser: ...
